### ISSUE TITLE
Not available on Curseforge

### ISSUE THREAD

**Issue by jstsmthrgk** [MapperTV/mapperbase#1]
Hello, could you maybe also upload your first release to Github, so that I can try out Road Stuff? I really like what you did there, but it seems Curseforge takes some time to review mapperbase.

**Comment by MapperTV** [comment]
Yeah Curse took a bit of time as it was week-end. In case anyone look of it it's at https://www.curseforge.com/minecraft/mc-mods/mapper-base .
