### ISSUE TITLE
[1.16.5] Your steel fences conflict with Immersive steel fences.

### ISSUE THREAD

**Issue by ProsperCraft** [MapperTV/mapperbase#5]
Your steel fences for Mapper base use the same recipe as immersive engineering, but don't work in immersive recipes.

**Comment by MapperTV** [comment]
I was thinking about using a tag so IE can implement it in its recipes but is the steel fence also used in multiblock structures? If yes then I'm no sure it deals with tags when building them so I will just change my recipe.

Edit: before I'll try to see with IE devs if we can do something about compatibility.

**Comment by MapperTV** [comment]
In the next release I modified the recipe as steel will be harder to get. This will fix the conflict in the process. I still keep this issue opened in case of getting some return from the IE devs.

**Comment by MapperTV** [comment]
Immersive Engineering should accept any fence in multiblock now if the fence has the correct tag. This means my fences should now be compatible.
